repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
    exclude: ^notebooks/
  - id: mixed-line-ending
  - id: check-added-large-files
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config
    args: [--exclude=notebooks/.*\.py]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.8.0
  hooks:
  - id: isort
    exclude: ^notebooks/
- repo: https://github.com/ambv/black
  rev: 21.5b1
  hooks:
  - id: black
    exclude: ^notebooks/
    language: python
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.8.3'
  hooks:
  - id: flake8
    exclude: ^notebooks/